"""add delete cascade on user_storage

Revision ID: 1842f34b3597
Revises: b18dc792d773
Create Date: 2026-04-29 16:12:17.736497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1842f34b3597'
down_revision: Union[str, Sequence[str], None] = 'b18dc792d773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_storage_user_id_fkey'), 'user_storage', type_='foreignkey')
    op.create_foreign_key(None, 'user_storage', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_storage', type_='foreignkey')
    op.create_foreign_key(op.f('user_storage_user_id_fkey'), 'user_storage', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
