"""Add max_space quota to table roles

Revision ID: 1a55aebc0095
Revises: 5436a01be1c4
Create Date: 2026-04-27 11:09:36.114691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a55aebc0095'
down_revision: Union[str, Sequence[str], None] = '5436a01be1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'roles',
        sa.Column(
            'max_space',
            sa.BigInteger(),
            nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'max_space')
    # ### end Alembic commands ###
