"""add immediate lazy loading between user and user storage

Revision ID: 223ed734e58a
Revises: 1842f34b3597
Create Date: 2026-04-30 09:36:07.491993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223ed734e58a'
down_revision: Union[str, Sequence[str], None] = '1842f34b3597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
