"""remove not null constraint on files_user_id_fkey

Revision ID: b18dc792d773
Revises: 483011feab8b
Create Date: 2026-04-28 16:15:00.514378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18dc792d773'
down_revision: Union[str, Sequence[str], None] = '483011feab8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'user_id',
                    existing_type=sa.BIGINT(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'user_id',
                    existing_type=sa.BIGINT(),
                    nullable=False)
    # ### end Alembic commands ###
