"""Add Files Table

Revision ID: 0f03fe7f109b
Revises: 8a940f3fdf72
Create Date: 2026-01-13 10:50:03.049211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f03fe7f109b'
down_revision: Union[str, Sequence[str], None] = '8a940f3fdf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('logical_name', sa.String(), nullable=False),
    sa.Column('is_directory', sa.Boolean(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('storage_bucket', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unique_active_entry_per_folder', 'files', ['parent_id', 'logical_name'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_active_entry_per_folder', table_name='files', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('files')
    # ### end Alembic commands ###
