services:
  db:
    image: postgres
    container_name: claspy_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - claspy_db_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Paris
    networks:
      - claspy-net

volumes:
  claspy_db_data:

networks:
  claspy-net:
    external: true


# docker compose --env-file .env -f db/docker-compose.db.yml up -d